//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HSH_Desa_y_Test.ContextoDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class foto
    {
        public int id { get; set; }
        public int idPropiedad { get; set; }
        public byte[] foto1 { get; set; }
    
        public virtual Propiedad Propiedad { get; set; }
    }
}
