//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HSH_Desa_y_Test.ContextoDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ganadorDeSubasta
    {
        public int id { get; set; }
        public string idUsuario { get; set; }
        public int idSubasta { get; set; }
        public int idPujaEnSubasta { get; set; }
    
        public virtual usuarioParticipaEnSubasta usuarioParticipaEnSubasta { get; set; }
        public virtual subasta subasta { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
