//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HSH_Desa_y_Test.ContextoDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotSale
    {
        public int id { get; set; }
        public string idUsuario { get; set; }
        public int idPropiedad { get; set; }
        public System.DateTime fechaInicio { get; set; }
        public System.DateTime fechaFin { get; set; }
        public decimal monto { get; set; }
        public int semanaReservada { get; set; }
    
        public virtual Propiedad Propiedad { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
