//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HSH_Desa_y_Test.ContextoDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tarjeta
    {
        public int id { get; set; }
        public string numero { get; set; }
        public System.DateTime vencimiento { get; set; }
        public string codigoSeguridad { get; set; }
        public string idPersona { get; set; }
    
        public virtual usuario usuario { get; set; }
    }
}
