//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HSH_Desa_y_Test.ContextoDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tarjeta
    {
        public int id { get; set; }
        public string numero { get; set; }
        public System.DateTime vencimiento { get; set; }
        public string codigoSeguridad { get; set; }
        public string idPersona { get; set; }
    
        public virtual usuario usuario { get; set; }
    }
}
