//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HSH_Desa_y_Test.ContextoDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public usuario()
        {
            this.tarjetas = new HashSet<tarjeta>();
            this.usuarioParticipaEnSubastas = new HashSet<usuarioParticipaEnSubasta>();
            this.ganadorDeSubastas = new HashSet<ganadorDeSubasta>();
            this.HotSales = new HashSet<HotSale>();
            this.ReservaDirectas = new HashSet<ReservaDirecta>();
        }
    
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string contraseña { get; set; }
        public string mail { get; set; }
        public System.DateTime fecha_nacimiento { get; set; }
        public bool premium { get; set; }
        public int token { get; set; }
        public System.DateTime fecha_registro { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tarjeta> tarjetas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<usuarioParticipaEnSubasta> usuarioParticipaEnSubastas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ganadorDeSubasta> ganadorDeSubastas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HotSale> HotSales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReservaDirecta> ReservaDirectas { get; set; }
    }
}
